# Generated by Django 3.2.23 on 2024-01-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moderation_status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
