# Generated by Django 3.2.23 on 2024-01-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240115_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='moderation_status',
        ),
    ]
